### ISSUE TITLE
Python >= 3.x doesn't work

### ISSUE THREAD

**Issue by davidthor** [architect-team/python-launcher#1]
It seems we're having some issues with python v3.x. The expected behavior is that the launcher should work using Python 3.4 and up. 

## Logs
```sh-session
$ architect start
Deploying addition-service
Deploying subtraction-service
/home/ryan/.nvm/versions/node/v8.15.0/lib/node_modules/@architect-io/cli/node_modules/@oclif/errors/lib/index.js:29
        throw err;
        ^

Error: Traceback (most recent call last):
  File "/home/ryan/.nvm/versions/node/v8.15.0/lib/node_modules/@architect-io/cli/node_modules/.bin/architect-python-launcher", line 25, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    at Object.error (/home/ryan/.nvm/versions/node/v8.15.0/lib/node_modules/@architect-io/cli/node_modules/@oclif/errors/lib/index.js:22:17)
    at Start.error (/home/ryan/.nvm/versions/node/v8.15.0/lib/node_modules/@architect-io/cli/node_modules/@oclif/command/lib/command.js:47:23)
    at Socket.cmd.stderr.on.data (/home/ryan/.nvm/versions/node/v8.15.0/lib/node_modules/@architect-io/cli/lib/commands/start.js:108:26)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
```

**Comment by davidthor** [comment]
I've been researching the culprit here a lot more and it seems that it has to do with the changes made between python 2 and 3 regarding relative module imports. There's a line at the top of generated `*_pb2_grpc.py` files that reads `import service_pb2 as service__pb2` that would need to read `from . import service_pb2 as service__pb2` to function properly in python 3. There have been several issues raised across both the GRPC and protocolbuffers repositories citing similar issues both for GRPC generation and raw protocolbuffer file generation when dealing with complex .proto file relationships, but there hasn't been a resolution that I've seen. I'm citing the issues and PRs I've found for reference:

* https://github.com/grpc/grpc/issues/9575#issuecomment-293934506
* https://github.com/protocolbuffers/protobuf/issues/1491
* https://github.com/protocolbuffers/protobuf/pull/1511
* https://github.com/protocolbuffers/protobuf/pull/3728

There does seem to be a way to leverage the current standing of the protoc command to generate files that use proper module references for python 3, but it leverages the input folder path to the .proto file rather than the output path to generate the module naming which is not what we would want in our case:

https://github.com/grpc/grpc/blob/v1.18.x/src/compiler/python_generator.cc#L613-L619

With this in mind, my short term solution will involve copying the .proto file to the tmp directory on the host into a subfolder matching the service name found in the corresponding `architect.json`, running the protoc command targeting this new .proto file, and then removing the tmp copy of the .proto file. Once I've done that, I'll circle back and attempt to patch the GRPC generator for python with a configuration flag allowing the protoc command to accept an output module parameter overriding the module naming to a desired output. Stay tuned for a PR to this launcher.

**Comment by davidthor** [comment]
Latest changes have been merged and python3 appears to be working. Will circle back at a later time to work with GRPC to update their generator code so that folder copying doesn't need to occur.
